"""initial schema

Revision ID: 5972fdbc4062
Revises: 
Create Date: 2026-10-01 08:18:37.792606
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5972fdbc4062'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bootstrap_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bootstrap_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bootstrap_keys_created_at'), ['created_at'], unique=False)

    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tenants_created_at'), ['created_at'], unique=False)

    op.create_table('master_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('options', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('master_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_master_fields_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_master_fields_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_steps_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_steps_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('step_fields',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['master_fields.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('step_fields', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_step_fields_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_fields_step_id'), ['step_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_step_fields_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('step_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['step_id'], ['steps.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_step_id'), ['step_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_tenant_id'), ['tenant_id'], unique=False)

    op.create_table('ticket_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=30), nullable=False),
    sa.Column('from_step_id', sa.Integer(), nullable=True),
    sa.Column('to_step_id', sa.Integer(), nullable=True),
    sa.Column('snapshot', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_events_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_events_ticket_id'), ['ticket_id'], unique=False)

    op.create_table('ticket_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('ticket_id', sa.Integer(), nullable=False),
    sa.Column('field_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['field_id'], ['master_fields.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ticket_values', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ticket_values_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_values_tenant_id'), ['tenant_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ticket_values_ticket_id'), ['ticket_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ticket_values', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_values_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_values_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_values_created_at'))

    op.drop_table('ticket_values')
    with op.batch_alter_table('ticket_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ticket_events_ticket_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_events_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_ticket_events_created_at'))

    op.drop_table('ticket_events')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_tickets_step_id'))
        batch_op.drop_index(batch_op.f('ix_tickets_created_at'))

    op.drop_table('tickets')
    with op.batch_alter_table('step_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_step_fields_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_step_fields_step_id'))
        batch_op.drop_index(batch_op.f('ix_step_fields_created_at'))

    op.drop_table('step_fields')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('steps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_steps_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_steps_created_at'))

    op.drop_table('steps')
    with op.batch_alter_table('master_fields', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_master_fields_tenant_id'))
        batch_op.drop_index(batch_op.f('ix_master_fields_created_at'))

    op.drop_table('master_fields')
    with op.batch_alter_table('tenants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tenants_created_at'))

    op.drop_table('tenants')
    with op.batch_alter_table('bootstrap_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bootstrap_keys_created_at'))

    op.drop_table('bootstrap_keys')
    # ### end Alembic commands ###
